### ISSUE TITLE
Current Project Status

### ISSUE THREAD

**Issue by marler8997** [afrogeek/SharpNative#3]
I see the last commit was October 2015, is this project dead?  Could you provide a project status somewhere, maybe in the README.md?  It also seems the link in the repo description (http://afrogeek.github.io/SharpNative) doesn't work.  I'm looking for a C# to D compiler, if this project is dead, is there another project that has taken this task on?

**Comment by afrog33k** [comment]
Hi there,  I'd say for the D target its probably dead, the targets i've been working on lately are typescript / javascript and c++. But quite a bit busy with other work unfortunately. I'll fix the link to  http://afrog33k.github.io/SharpNative. Also unfortunately it seems there was not much interest in this product and with fully open source Xamarin. Not much for me to go by. Thanks for dropping by though 👍

**Comment by marler8997** [comment]
Cool thanks for the info.  I'm an engineer at HP and we have a very large codebase for our enterprise printers that uses C#.  We are changing platforms and are looking into converting our code base to another language.  I'd like to go to D, but we'll need a tool for this.  If it's alright with you, I'll probably look into writing a tool and/or using this tool for this exploration.

**Comment by afrog33k** [comment]
That would be great. I'd love to see what you come up with :)
